name: powerpc/perf

# Controls when the action will run.
on:
  # This allows the build to be triggered manually via the github UI.
  workflow_dispatch:

  push:
    # This triggers the build on a push to any branch
    branches:
    - '**'
    # As long as one of these paths matches
    paths:
      # Only build if perf or other pieces it uses have been modified
      - 'tools/perf/**'
      - 'tools/arch/**'
      - 'tools/build/**'
      - 'tools/include/**'
      - 'tools/lib/**'
      - 'tools/scripts/**'

jobs:
  perf:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [ubuntu-21.10, ubuntu-21.04, ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
        subarch: [ppc64, ppc64le]

    env:
      ARCH: powerpc
      TARGET: perf
      SUBARCH: ${{ matrix.subarch }}
      IMAGE: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: ./arch/powerpc/tools/ci-build.sh

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.subarch }}-${{ matrix.image }}
        path: |
          ~/output
